### ISSUE TITLE
Failed to display a survey on iOS 14 Beta.  App crash.

### ISSUE THREAD

**Issue by mike-dutka** [apptentive/apptentive-ios#287] opened 2020-08-26 13:26 UTC
Device: iPad Pro 9.7in
iOS 14 Beta (18A5351d)

App fails to show a survey after `Apptentive.shared.engage(event: eventName, withCustomData: nil, from: controller)` than stops responding and crashes in a minute. Profiling shows that there is some problem with an Apptentive collection layout flow which leads to huge memory consumption and app crashing.
<img width="794" alt="Screenshot 2020-08-26 at 16 13 56" src="https://user-images.githubusercontent.com/3025929/91308862-8df71380-e7b8-11ea-9df0-c20db7c3df68.png">
<img width="806" alt="Screenshot 2020-08-26 at 16 21 56" src="https://user-images.githubusercontent.com/3025929/91308876-92233100-e7b8-11ea-8fba-fe3d78ab51fd.png">

**Comment by CaseyApptentive** [comment] 2020-08-26 16:38
Hi @mike-dutka. Thanks for the report. We'll take a closer look as soon as possible. 

What version of the SDK are you using?

**Comment by mike-dutka** [comment] 2020-08-26 17:04
Hi @CaseyApptentive. Tried 5.2.12 and 5.2.14

**Comment by CaseyApptentive** [comment] 2020-08-26 20:48
Thanks for the versions, @mike-dutka ! 

We're able to reproduce the issue now and will let you know as soon as we have a fix. This is a priority for us and we'll have it available as soon as we can have everything verified.

**Comment by frankus** [comment] 2020-09-08 20:23
This is fixed on the new `ios-14` branch released today. Please take a look and let us know if it works for you. 

Thanks again for the detailed report!

**Comment by braker1nine** [comment] 2020-09-11 13:34
@frankus we're having issues with the changes to the header imports when we pull this branch in via cocoapods. Our builds are failing because some header files aren't found.

Changing 
```Objective-C
#import <Apptentive/ApptentiveStyleSheet.h>
```
to this
```Objective-C
#import <ApptentiveStyleSheet.h>
```
resolves the issue

Has anyone else experienced this? I'm trying to figure out if it's something in our cocoapods setup that's wrong

**Comment by frankus** [comment] 2020-09-14 19:38
I am able to reproduce this by removing the `use_frameworks!` directive from the Podfile. 

It's been a few years since I've investigated this, but it sounds like `use_frameworks!` has fallen out of favor somewhat due to longer app startup times. Can you tell me a bit more about your setup so we can look at improving support for this? Mostly around language mix (Swift/Obj-C) and how you're actually importing things.

**Comment by braker1nine** [comment] 2020-09-15 12:51
Ahhh right right. Our codebase is majority Objective-C with maybe a slowly increasing chunk of swift. Our actual use of the Apptentive SDK is all in a single Objective-C wrapper where we're importing the root Apptentive header file with an `#import "Apptentive.h"`

**Comment by frankus** [comment] 2020-09-16 00:27
We've just released the changes as version 5.3.0. 

If adding the `use_frameworks!` directive to your podfile is not something you're comfortable with, there are instructions [here](https://learn.apptentive.com/knowledge-base/cocoapods-guide/) to add a post-install hook and a preprocessor macro that should fix the include issues. 

If you can use  `use_frameworks!` then it should be smooth sailing without any extra work.

**Comment by braker1nine** [comment] 2020-09-16 00:41
Bummer. That's probably not a change we want to make just to support a single package. I'd definitely say I'd recommend y'all figure out how to get the library building without requiring it to be a framework. But admittedly I don't have a full grasp of the challenges there. And I know we're all on a tight timeline with iOS 14 😅 

For the long term we may either build more manually or maybe use a git submodule

**Comment by frankus** [comment] 2020-09-16 15:25
@braker1nine we've updated the way headers are managed, so you should be able to include it as you have been all along. The only change you might notice is that the `Apptentive.h` header is no longer copied, so you'll have to include the two headers that live under that umbrella header manually (`ApptentiveMain.h` and `ApptentiveStyleSheet.h`).

**Comment by braker1nine** [comment] 2020-09-16 15:31
@frankus I saw that this morning and already have a branch in our codebase building off that branch! 👍 thanks we really appreciate the quick turnaround!

**Closed** 2022-11-15 20:41 UTC
