### ISSUE TITLE
Unable to disable framework

### ISSUE THREAD

**Issue by sima-11** [apptentive/apptentive-ios#283] opened 2020-07-22 17:51 UTC
Dear team,

I couldn't seem to find a function to disable the framework once `Apptentive.register(with:)` is called.
My assumption is if I pass in an invalid “configuration” parameter when calling “Apptentive.register(with:)”, it’ll probably disable the SDK?
Would be helpful if you could provide some insight?

Thanks!

**Comment by CaseyApptentive** [comment] 2020-07-22 22:34
Hi @sima-11. Great question. Let me see if I can help track down an answer. 

Stay tuned.

**Comment by CaseyApptentive** [comment] 2020-07-23 00:24
Hi @sima-11 . I spoke with my team to be sure, and by design, after the `Apptentive.register(with:)` method has been called, the SDK cannot be disabled. It will continue to run until the app fully exits.

Can you tell me a bit more about why you're trying to disable the SDK? Though we don't support doing that, I may be able to offer help solving whatever problem you're trying to solve.

**Comment by sima-11** [comment] 2020-07-24 08:07
Thanks @CaseyApptentive. It's basically required by TCF 2.0, and we need to enable/disable the SDK at runtime, ideally without force quitting our app.

**Comment by CaseyApptentive** [comment] 2020-07-27 23:05
Thanks for the clarification @sima-11. Are you or your team also discussing this with Pat from Apptentive's Customer Success team? I work closely with him and want to be sure we're not crossing wires. 

If it's okay with you and you are working with him, let's use that thread moving forward so everyone is on the same page.

**Comment by sima-11** [comment] 2020-07-28 14:11
Hi @CaseyApptentive, yes, I've also had some conversation with Pat, and he mentioned he'll have discussion with the team. 👍

**Comment by CaseyApptentive** [comment] 2020-07-28 16:38
Thanks, @sima-11. I'm going to close this issue for now to help keep discussion streamlined.

**Closed by CaseyApptentive** 2020-07-28 16:38 UTC
