### ISSUE TITLE
Crash related to WebKit::ProcessThrottler::updateAssertion()

### ISSUE THREAD

**Issue by matheda** [apptentive/apptentive-ios#199] opened 2017-09-05 00:57 UTC
Sorry to drop another odd crash on you.  We are starting to see a non-trivial number of crashes with the following stack trace:

![screen shot 2017-09-04 at 8 40 27 pm](https://user-images.githubusercontent.com/1895008/30040867-b706f600-91b2-11e7-993c-f9de97105114.png)

I have gone through a couple of dozen of the instances, and for most of them the only non-Apple code being executed on any thread is something in the Apptentive SDK.  The odd thing is that it is not consistent.  Below are three examples.  Two of them look similar but have a different method at the top of the stack:

Example 1:
![screen shot 2017-09-04 at 8 40 41 pm](https://user-images.githubusercontent.com/1895008/30040882-fa65423a-91b2-11e7-825e-073dd01f7e59.png)

Example 2:
![screen shot 2017-09-04 at 8 41 05 pm](https://user-images.githubusercontent.com/1895008/30040884-fc88fa02-91b2-11e7-9cf3-f5a343af3133.png)

Example 3:
![screen shot 2017-09-04 at 8 41 25 pm](https://user-images.githubusercontent.com/1895008/30040890-fede3434-91b2-11e7-8984-d66779f20eb4.png)

I did some quick research on the WebKit::ProcessThrottler::updateAssertion(), and it looks like it is related to the app going into the background:

```
void ProcessThrottler::updateAssertion()
{
    // If the process is currently runnable but will be suspended then first give it a chance to complete what it was doing
    // and clean up - move it to the background and send it a message to notify. Schedule a timeout so it can't stay running
    // in the background for too long.
    if (m_assertion && m_assertion->state() != AssertionState::Suspended && !m_foregroundCounter.value() && !m_backgroundCounter.value()) {
        ++m_suspendMessageCount;
        RELEASE_LOG("%p - ProcessThrottler::updateAssertion() sending PrepareToSuspend IPC", this);
        m_process.sendPrepareToSuspend();
        m_suspendTimer.startOneShot(processSuspensionTimeout);
        m_assertion->setState(AssertionState::Background);
        m_process.didSetAssertionState(AssertionState::Background);
        return;
    }

    bool shouldBeRunnable = m_foregroundCounter.value() || m_backgroundCounter.value();

    // If we're currently waiting for the Web process to do suspension cleanup, but no longer need to be suspended, tell the Web process to cancel the cleanup.
    if (m_suspendTimer.isActive() && shouldBeRunnable)
        m_process.sendCancelPrepareToSuspend();
    
    if (m_assertion && m_assertion->state() == AssertionState::Suspended && shouldBeRunnable)
        m_process.sendProcessDidResume();

    updateAssertionNow();
}
```
(copied from https://opensource.apple.com/source/WebKit2/WebKit2-7602.4.6/UIProcess/ProcessThrottler.cpp)

I am wondering if this is related to the other backgrounding issue that we are working on.  As always, let me know if I can provide any additional information, and we appreciate all of the fixes you have been putting out for us.

**Comment by matheda** [comment] 2017-09-05 01:01
One more data point: we are only seeing this crash in the version of our app that is using the 4.0.4 SDK.

**Comment by frankus** [comment] 2017-09-05 17:58
We had another customer report a similar issue. It has to do with a background task that, due to a code bug, results in the background task completion handler not getting called. So the system ends up killing the app after a period of time (https://github.com/apptentive/apptentive-ios/issues/198). 

I believe the two are related.

**Comment by frankus** [comment] 2017-09-07 18:43
Version 4.0.5 (just released) fixes a problem with the background task that is used to save the Core Data stack on app exit. I believe that the way the Core Data stack was previously exiting is what was causing this crash.

**Comment by matheda** [comment] 2017-09-11 12:47
Unfortunately we are still seeing this crash in the latest version of our app which is using the 4.0.5 SDK:

![screen shot 2017-09-11 at 8 30 06 am](https://user-images.githubusercontent.com/1895008/30274913-5cabc936-96cd-11e7-81f9-df1a255aa4fb.png)
![screen shot 2017-09-11 at 8 30 20 am](https://user-images.githubusercontent.com/1895008/30274915-5fd6b044-96cd-11e7-9136-958ec9c8982c.png)

**Comment by frankus** [comment] 2017-09-11 20:28
I will keep investigating. Thanks for the update.

**Comment by frankus** [comment] 2017-09-21 18:33
We have released a new tag that should address this issue: https://github.com/apptentive/apptentive-ios/releases/tag/v4.0.6-rc. 

If you are able to reproduce this crash it would be helpful to make sure it is no longer occurring.

**Comment by frankus** [comment] 2017-09-27 21:16
We now have an [official release](https://github.com/apptentive/apptentive-ios/releases/tag/v4.0.6) incorporating these fixes.

**Comment by frankus** [comment] 2017-10-11 17:18
I' closing this for the time being. If you see additional instances of this crash please reopen this issue.

**Closed by frankus** 2017-10-11 17:18 UTC
