### ISSUE TITLE
iOS 8.4.1 layout problem

### ISSUE THREAD

**Issue by napolux** [apptentive/apptentive-ios#162] opened 2015-10-08 09:46 UTC
We open an email message from our viewcontroller, but ONLY in iOS 8.4.1 on iPad is broken and not in the middle of the screen...

iOS 8.3.x and iOS 9.x is fine...

![info_cosanepensi_ipad4](https://cloud.githubusercontent.com/assets/1070836/10363000/17bcf9ee-6db2-11e5-8e2e-21578d8c0bf3.png)

**Comment by pkamb** [comment] 2015-10-08 19:59
Hi @napolux, sorry for the issue here.

We have seen this issue, but like you said only on certain iPad hardware models and certain iOS versions. It's been very difficult to track down, and the root cause lies somewhere in Apple's code.

https://github.com/apptentive/apptentive-ios/issues/148

http://stackoverflow.com/questions/30237816/custom-uiwindow-on-ios-8-3-ipad-works-on-simulator-but-not-device

Are you able to update your project to the Apptentive SDK 2.0+ version? We've modernized all of this code with Auto Layout in v2.0+, which fixes this issue. Please let us know if you have any difficulties upgrading to 2.0. Thanks!

**Comment by frankus** [comment] 2015-12-12 01:07
This is fixed in 2.0 and later SDKs.

**Closed by frankus** 2015-12-12 01:07 UTC
