### ISSUE TITLE
Crash in connection:didFailWithError: mthod

### ISSUE THREAD

**Issue by AjeetSharma331** [apptentive/apptentive-ios#185] opened 2016-10-07 11:00 UTC
We are facing one crash in [ApptentiveURLConnection connection:didFailWithError:] method as per crash report.
The method looks like - (void)connection:(NSURLConnection *)aConnection didFailWithError:(NSError *)error which is in Apptentive class in code. 
We are not able to reproduce at our end. But crash was found at production end.
The os version was iOS 10.x where the crash is happening.

**Comment by frankus** [comment] 2016-10-07 17:08
I'm taking a look at this currently. Could you let me know in which version of the SDK (tag or git SHA) the crash is happening?

**Comment by AjeetSharma331** [comment] 2016-10-10 06:14
The Apptentive SDK version is “v3.0.0”(28a73df).
Let me know if you have any other query.

**Comment by frankus** [comment] 2016-10-10 16:24
Do you have any additional information on the crash you could send my way? I'm not seeing any smoking guns in the code for that method.

**Comment by AjeetSharma331** [comment] 2016-10-12 05:35
The crash report looks like:
0   **ApplicationName                	0x0000000100204ff8 ApptentiveLocalizedString + 0**
1   Foundation                    	0x000000018e2dcb5c -[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:modes:] + 984
2   Foundation                    	0x000000018e2e0acc -[NSObject(NSThreadPerformAdditions) performSelectorOnMainThread:withObject:waitUntilDone:] + 144
3   **ApplicationName                 0x0000000100219b7c -[ApptentiveURLConnection connection:didFailWithError:] + 312**
4   CFNetwork                     	0x000000018e11d76c __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 80
5   CFNetwork                     	0x000000018e11d6fc -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 200
6   CFNetwork                     	0x000000018e11d8bc -[NSURLConnectionInternal _withConnectionAndDelegate:] + 56
7   CFNetwork                     	0x000000018e0dc5b4 _NSURLConnectionDidFail(_CFURLConnection*, __CFError*, void const*) + 76
8   CFNetwork                     	0x000000018e044a9c ___ZN27URLConnectionClient_Classic17_delegate_didFailEP9__CFErrorU13block_pointerFvvE_block_invoke + 112
9   CFNetwork                     	0x000000018e042678 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 108
10  libdispatch.dylib             	0x000000018c7691c0 _dispatch_client_callout + 16

**Comment by frankus** [comment] 2016-10-17 18:48
It's hard to know since I wasn't able to reproduce the crash, but this may be related to accessing NSBundle methods from the wrong thread. 

Out of an abundance of caution, and because it's not really necessary, I will be removing the localization of the error messages (which aren't user-visible anyway) from a future release. 

Thanks for the report.

**Comment by frankus** [comment] 2016-11-08 01:24
The latest release (3.3.2) includes a fix for this.

**Closed by frankus** 2016-11-08 01:24 UTC
